### ISSUE TITLE
Navbar size needs to be reduced.

### ISSUE THREAD

**Issue by JIBIN-P** [projectors1/Investment-Advisor#2]
The navbar size is not changing when we are modifying the value of min-height in navbar.css file @i1-D look into the issue and resolve it when you can.

**Comment by i1-D** [comment]
I checked a lot of websites and most of them have their height in the range 50-60. Even github's navbar height is 54px. The default navbar size of bootstrap looks too small. I think 60px is perfect. It isn't too big nor too small.

**Comment by JIBIN-P** [comment]
@i1-D actually the navbar of 60px is messing with the startup page in mobile view you can check that in our static page but I will be redesigning the whole startup page so it's ok for now but the about us page may face the problem so a little smaller is recommended 55px I hope will be ok.

_Sent from my OnePlus ONE A2003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
